name: causeascene
description: I paint on paintings

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  url_launcher: ^6.1.0
  font_awesome_flutter: ^10.1.0
  flutter_staggered_grid_view: ^0.6.2
  transparent_image: ^2.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/sold/
